run_env: local
docker_registry: ghcr.io/oss-crs/test

# `oss-crs-infra` must be required
oss_crs_infra: 
  cpuset: "0-3" 
  memory:  "16G"

crs-libfuzzer:
  source:
    url: git@github.com:Team-Atlanta/crs-libfuzzer.git
    ref: refined-oss-crs
  cpuset: "4-7" 
  memory:  "16G"
  # crs-libfuzzer does not use llm.
  #llm_budget: 100 


# crs-libfuzzer does not use llm.
#llm_config:
#  litellm_config: ~/example-litellm-config.yaml
